on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: maven:3-openjdk-17-slim
    container:
      image: postgres:14.1-alpine
      env:
        POSTGRES_USER: ShevchenkoDN
        POSTGRES_PASSWORD: She031fit
        POSTGRES_DB: storeDb
        PGDATA: /var/lib/postgresql/data/pgdata
    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: ShevchenkoDN
          POSTGRES_PASSWORD: She031fit
          POSTGRES_DB: storeDb
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Maven build
        run: mvn clean compile
      - name: All tests
        run: mvn test
      - name: Package app
        run: mvn package
